### ISSUE TITLE
source-map in production

### ISSUE THREAD

**Issue by lucduong** [maingocthanhtan96/LaraJS#2]
Hi @maingocthanhtan96, 

Anh mới lượn một vòng, thấy em có tâm huyết với dự án quá. :D cũng khá là nhiều commit. 👍 

```js
if (isProduction) {
  mix.version();
} else {
  mix.sourceMaps().webpackConfig({
    devtool: 'eval-cheap-source-map', // Fastest for development
  });
}
```

Khúc này là build cho frontend, thực tế là nên có source-map để việc debug trên production dễ dàng hơn. Tuy nhiên sẽ có một vài ý nhỏ ở đây:
- Sourcemap chỉ được load khi mở `Debugger` (`F12`) nên không sợ load quá nhiều
- Nếu một người biết về `Debugger` thì sẽ đọc được source code khi có source-map? Điều này là đúng, nhưng đối với `production`, mình sẽ secure các đường dẫn `source-map` bằng auth-header / VPN. Chỉ người có quyền thì mới có quyền inspect những file này.
- Thực ra khi deploy mình cũng không cần thiết phải deploy những file `source-map`, mình có thể sử dụng một số tools khác như `sentry` (open-source) để tracking. Sau khi mình build -> collect source-map -> upload lên `sentry`. Như vậy thì khi nào có issue sẽ inspect dễ dàng hơn khi không có `source-map`

**Comment by maingocthanhtan96** [comment]
Đầu tiên cảm ơn Anh
Em thấy cách của a cũng khá hay nhưng e chưa có hướng làm không biết a có demo không?
Hiện tại dưới fe thì có có check => Khi có log error thì e sẽ call api để lưu lại error log
Cảm ơn Anh

**Comment by lucduong** [comment]
@maingocthanhtan96 Dễ nhất là em có thể dùng `Sentry.io`, hiện tại anh cũng đang dùng luôn.

- Đối với Vue thì em có thể tham khảo ở đây cách integration: https://docs.sentry.io/platforms/javascript/guides/vue/
- Trường hợp em generate source map và upload lên sentry: https://docs.sentry.io/platforms/javascript/guides/vue/sourcemaps/uploading/

`Strong recommend: upload source map lên sentry.`

Các bước:
- Build production including source-map
- Sentry upload source-map
- Remove source-map in `dist` / `build`
- Deploy the bundled file without `source-map`

Log Event thì thế này:
![image](https://user-images.githubusercontent.com/2667418/128791989-c5405ada-fdbc-47c3-855f-e3403c8f449e.png)

**Comment by maingocthanhtan96** [comment]
Hay quá a ơi. Để e tham khảo ạ <3
Cảm ơn anh.
